export default {
  login: "john-smilga",
  id: 42133389,
  node_id: "MDQ6VXNlcjQyMTMzMzg5",
  avatar_url: "https://avatars3.githubusercontent.com/u/42133389?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/john-smilga",
  // url: "https://api.github.com/users/maruf1137",
  html_url: "https://github.com/john-smilga",
  followers_url: "https://api.github.com/users/john-smilga/followers",
  following_url:
    "https://api.github.com/users/john-smilga/following{/other_user}",
  gists_url: "https://api.github.com/users/john-smilga/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/john-smilga/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/john-smilga/subscriptions",
  organizations_url: "https://api.github.com/users/john-smilga/orgs",
  repos_url: "https://api.github.com/users/john-smilga/repos",
  events_url: "https://api.github.com/users/john-smilga/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/john-smilga/received_events",
  type: "User",
  site_admin: false,
  name: "John Smilga",
  company: "Coding Addict",
  blog: "www.johnsmilga.com",
  location: "Los Angeles",
  email: null,
  hireable: null,
  bio: "Creator of Coding Addict",
  twitter_username: "john_smilga",
  public_repos: 152,
  public_gists: 0,
  followers: 1495,
  following: 0,
  created_at: "2018-08-06T06:48:23Z",
  updated_at: "2020-07-08T05:01:32Z",
};

/*
export default {
  login: "maruf1137",
  id: 79596658,
  node_id: "MDQ6VXNlcjc5NTk2NjU4",
  avatar_url: "https://avatars.githubusercontent.com/u/79596658?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/maruf1137",
  html_url: "https://github.com/maruf1137",
  followers_url: "https://api.github.com/users/maruf1137/followers",
  following_url:
    "https://api.github.com/users/maruf1137/following{/other_user}",
  gists_url: "https://api.github.com/users/maruf1137/gists{/gist_id}",
  starred_url: "https://api.github.com/users/maruf1137/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/maruf1137/subscriptions",
  organizations_url: "https://api.github.com/users/maruf1137/orgs",
  repos_url: "https://api.github.com/users/maruf1137/repos",
  events_url: "https://api.github.com/users/maruf1137/events{/privacy}",
  received_events_url: "https://api.github.com/users/maruf1137/received_events",
  type: "User",
  site_admin: false,
  name: "Maruf khan",
  company: "Fiverr",
  blog: "https://www.fiverr.com/share/NEkm3G",
  location: "Bangladesh",
  email: null,
  hireable: null,
  bio: "Hello, Welcome To My Github profile,\r\nI am a frontend developer work at fiverr...",
  twitter_username: "maruf1137",
  public_repos: 34,
  public_gists: 0,
  followers: 2,
  following: 5,
  created_at: "2021-02-24T17:11:48Z",
  updated_at: "2021-09-16T13:53:35Z",
};
*/
